server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # LA MAGIA DE VUE ROUTER: Si no encuentra el archivo físico, redirige a index.html
        try_files $uri $uri/ /index.html;
    }

    # Caché agresivo para tus imágenes WebP (Lighthouse amará esto)
    location ~* \.(?:ico|css|js|gif|webp|jpe?g|png)$ {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}